name: ml_lecture
channels:
- conda-forge
dependencies:
    - numpy
    - pandas
    - matplotlib
    - cartopy
    - pytorch
    - sklearn
    - seaborn
    - scipy
    - statsmodels
    - jupyterlab
    - pip:
        - pytesmo
        - ipywidgets
        