name: ml_lecture
channels:
- conda-forge
dependencies:
    - python=3.12
    - numpy
    - pandas
    - matplotlib
    - cartopy
    - pytorch
    - scikit-learn=1.8.0
    - seaborn
    - scipy
    - statsmodels
    - jupyterlab
    - pip:
        - pytesmo
        - ipywidgets
        - tqdm  
        
